#+AUTHOR: wanglifeng
#+TITLE: Ledger: Command-Line Accounting

* Comment
** Single line
#+BEGIN_EXAMPLE
 ; This is a single line comment,
 # and this,
 % and this,
 | and this,
 * and this.
#+END_EXAMPLE

Block comments can be made by use ‘comment’ ...  ‘end comment’.
#+BEGIN_EXAMPLE
comment
This is a block comment with
multiple lines
end comment
#+END_EXAMPLE

* Five Accounts
- Expenses: where money goes,
- Assets: where money sits,
- Income: where money comes from,
- Liabilities: money you owe,
- Equity: the real value of your property.

* Accounting Equations
#+BEGIN_EXAMPLE
Net worth = Assets - Liabilities
Net income = Income - Expenses
#+END_EXAMPLE

* Three states
- Uncleared
- Pending
- Cleared

* Emacs ledger mode
emacs has got a mode for editing ledger files and provide some tools for reporting, calculation etc.

* Edit transaction
** key binding
#+BEGIN_EXAMPLE
formatting transactions:  TAB
formatting buffer: ledger-mode-clean-buffer
add transaction: C-c C-a
copy transaction: C-c C-k
delete transactions:  C-c C-d
sorting transactions:  C-c C-s
narrowing transactons:  C-c C-f (regex to match, example: 2016/09, auto, assets)
check account balance: C-c C-p
edit amount: invoke Calc: C-c C-b,  yank Calc value: y
#+END_EXAMPLE

** commands
#+BEGIN_EXAMPLE
ledger-mode-clean-buffer
ledger-report
#+END_EXAMPLE

* Reconcile

- obligating funds and expending funds
- C-c C-r pick an account

* Report

- ledger-report
- R for reverse order
- C-c C-o C-r report
- C-c C-o C-e edit report
- C-c C-o C-k kill report
- C-c C-o C-s save report


* Commodity price history
#+BEGIN_SRC sh
ledger --price-db price.db -V balance brokerage
#+END_SRC

#+BEGIN_EXAMPLE
P 2004/06/21 02:17:58 TWCUX $27.76
P 2004/06/21 02:17:59 AGTHX $25.41
P 2004/06/21 02:18:00 OPTFX $39.31
P 2004/06/21 02:18:01 FEQTX $22.49
P 2004/06/21 02:18:02 AAPL $32.91
#+END_EXAMPLE

* Equity
Often used as opening balances, negative means you are making money.
I use Equity:ForBalance for weekly balance.

* Petty cash
#+BEGIN_EXAMPLE
2004/03/15 ATM
Expenses:Cash                      $100.00
Assets:Checking

If at some point you make a large cash expense that you want to
track, just _move_ the amount of the expense from ‘Expenses:Cash’ into
the target account:

2004/03/20 Somebody
Expenses:Food                       $65.00
Expenses:Cash
#+END_EXAMPLE
* Narrow
- C-c C-f

* Statistics
- C-c C-l
